trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self

- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SonarCloudConnection'
    organization: 'shreyash10261'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'container-security-demo'
    cliProjectName: 'container-security-demo'
    cliSources: '.'

- task: SonarCloudAnalyze@3

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'