trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    docker build -t container-demo:v1 .
  displayName: 'Build Docker Image'

- script: |
    docker run --rm \
      -v /var/run/docker.sock:/var/run/docker.sock \
      aquasec/trivy image \
      --severity HIGH,CRITICAL \
      container-demo:v1
  displayName: 'Trivy Security Scan'