trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# Install Trivy
- script: |
    sudo apt-get update
    sudo apt-get install wget -y

    wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.66.0_Linux-64bit.deb

    sudo dpkg -i trivy_0.66.0_Linux-64bit.deb

    trivy --version
  displayName: 'Install Trivy'

# Build Docker Image
- script: |
    docker build -t container-demo:v1 .
  displayName: 'Build Docker Image'

# Scan Docker Image
- script: |
    trivy image --severity HIGH,CRITICAL container-demo:v1
  displayName: 'Trivy Security Scan'
